name: Build and check (PS2)

on:
    push:
        branches: [ "main" ]
    pull_request_target:
    workflow_dispatch:


jobs:
    build:
        # Building and testing cannot work if the repository owner is not apstygo
        # due to the missing secrets
        if: github.repository == 'apstygo/sfiii-decomp'
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        steps:
          - name: Clone main repo (PR)
            if: github.event_name == 'pull_request_target'
            uses: actions/checkout@v4
            with:
                ref: ${{ github.event.pull_request.head.sha }}
                submodules: recursive

          - name: Clone main repo
            if: github.event_name != 'pull_request_target'
            uses: actions/checkout@v4
            with:
                ref: ${{ github.ref }}
                submodules: recursive

          - name: Install Python dependencies
            run: pip install -r tools/requirements-python.txt

          - name: Enable i386 architecture and install Linux dependencies
            run: |
                sudo dpkg --add-architecture i386
                sudo apt-get update
                sudo apt-get install -y $(cat tools/requirements-debian.txt)

          - name: Setup build tools
            run: make setup_tools

          - name: Decrypt original ELF's binary
            run: openssl enc -d -aes-256-cbc -in encrypted.bin -out THIRD_U.BIN -pass pass:${{ secrets.BIN_PASSWORD }}

          - name: Split the binary
            run: make split

          - name: Build and compare binaries
            run: |
                set -o pipefail
                make build -j 2>&1 | tee build.log
            shell: bash

          - name: Upload build log
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: build-log
                path: build.log

          - name: Update progress in README
            if: github.event_name != 'pull_request_target'
            run: python3 tools/update_progress_in_readme.py

          - name: Update CRI progress
            if: github.event_name != 'pull_request_target'
            run: python3 tools/update_cri_progress.py

          - name: Commit progress updates
            if: github.event_name != 'pull_request_target'
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
                commit_message: Update progress
                file_pattern: 'README.md cri-progress.md'
